export const PAPERCUT_USER_PROPERTIES = [
  // Read/Write
  "balance",
  "primary-card-number",
  "secondary-card-number",
  "department",
  "disabled-print",
  "email",
  "full-name",
  "internal",
  "notes",
  "office",
  "delegated-users",
  "delegated-groups",
  "print-stats.job-count",
  "print-stats.page-count",
  "net-stats.data-mb",
  "net-stats.time-hours",
  "restricted",
  "home",
  "unauthenticated",
  "username-alias",
  "dont-hold-jobs-in-release-station",
  "dont-apply-printer-filter-rules",
  "printer-cost-adjustment-rate-percent",
  "dont-archive",
  "auto-release-jobs",
  "overdraft-amount",
  // Read-only
  "account-selection.mode",
  "account-selection.can-charge-personal",
  "account-selection.can-charge-shared-from-list",
  "account-selection.can-charge-shared-by-pin",
  "other-emails",
  "auto-shared-account",
] as const;
